# Generated by Django 4.0.6 on 2023-01-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
