# Generated by Django 4.0.6 on 2023-02-09 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cart_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='amount',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(3, message='Min cant be less than 3'), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
