# Generated by Django 4.0.6 on 2022-12-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='menu/images/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
