# Generated by Django 4.0.6 on 2022-12-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_food_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to='static/menu/images/'),
        ),
    ]
