# Generated by Django 4.0.6 on 2022-12-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_food_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
