# Generated by Django 4.0.6 on 2022-12-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
