# Generated by Django 4.0.6 on 2023-02-14 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_food_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='stock',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
