# Generated by Django 4.0.6 on 2023-01-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('products', models.JSONField()),
                ('email_address', models.EmailField(max_length=254)),
                ('payment_type', models.CharField(max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
