# Generated by Django 4.1.7 on 2023-02-25 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-pk']},
        ),
    ]
